### ISSUE TITLE
Feature request: multiline comments

### ISSUE THREAD

**Issue by bannmann** [tomokinakamaru/silverchain#50]
In addition to `// single line comments`, Silverchain should support `/* multiline comments */` as well.

I tried to use them to comment out sections of my AG file while debugging a problem, but I imagine it would be useful in other cases as well.

**Comment by tomokinakamaru** [comment]
Thanks for your requests :)

I added the support for multiline comments (#50), array types (#49), varargs (#48), and `throws`-clause (#47). Would you check the latest docker image and close the corresponding issues if it works fine for your case?

**Comment by bannmann** [comment]
Thank you very much, all four features work perfectly! 🥇🎉
