### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by bannmann** [tomokinakamaru/silverchain#61]
Building on PR #53, I'd like to ask for Silverchain to be published to Maven Central. 

Terminology notes: Maven Central (a.k.a. the Central Repository) is operated by the company "Sonatype". For individuals, publishing to Maven Central happens via the OSSRH ("Open Source Software Repository Hosting") servers.

We will need the following things:

- One-time setup for @tomokinakamaru as the one in control of and performing releases:
  - Get a free account on OSSRH: [Sign up page](https://issues.sonatype.org/secure/Signup!default.jspa)
  - Claim the namespace ~`com.github.tomokinakamaru`~ `io.github.tomokinakamaru` (valid for `.silverchain` and any other personal repositories)
    - Steps
      1. Create a ['New Project' ticket](https://issues.sonatype.org/secure/CreateIssue.jspa?issuetype=21&pid=10134)
      2. Prove ownership by creating an empty temporary GitHub repository with the same name as the ticket number, e.g. `OSSRH-12345` which resides at `https://github.com/tomokinakamaru/OSSRH-12345`
  - Personal OpenPGP key for code signing
    - Sonatype provides detailed explanations for [Working with PGP Signatures](https://central.sonatype.org/publish/requirements/gpg/), but for starters, you only need these three steps:
      1. [Installing GnuPG](https://central.sonatype.org/publish/requirements/gpg/#installing-gnupg)
      2. [Generating a Key Pair](https://central.sonatype.org/publish/requirements/gpg/#generating-a-key-pair)
      3. [Distributing Your Public Key](https://central.sonatype.org/publish/requirements/gpg/#distributing-your-public-key)
  - Set up gradle for code signing & publishing
 
    1. Export your secret key ring file:
        ```
        gpg --keyring secring.gpg --export-secret-keys \
          > ~/.gnupg/secring.gpg
        ```
    2. Locate your Gradle home directory (default is `$USER_HOME/.gradle`) and create/open the file `gradle.properties`
    3. Determine the key ID (`gpg -K`) and set the signing properties:
        ```
        signing.keyId=24875D73
        signing.password=secret
        signing.secretKeyRingFile=/Users/me/.gnupg/secring.gpg
        ```
    4. Add OSSRH credentials as follows:
        ```
        ossrhUsername=your-jira-id
        ossrhPassword=your-jira-password
        ```
- Extending the Gradle build script to support publishing
  - In an upcoming PR

Later, I'll provide more details on how to actually perform releases. I promise it's way simpler than the above. 😉

**Comment by tomokinakamaru** [comment]
Thanks for the detailed guide! It saved me a lot of time googling how to publish software :)

It's now ready (https://issues.sonatype.org/browse/OSSRH-74193?page=com.atlassian.jira.plugin.system.issuetabpanels), so I will merge PR #62 and publish to Central soon.

**Comment by tomokinakamaru** [comment]
I merged #62 and ran `./gradlew publish` on the master branch. Are these all I need to do? (I guess not, but I couldn't figure out what I am missing...)

**Comment by tomokinakamaru** [comment]
I pressed the release button in Nexus repository manager, but after that, I found that the artifact has the wrong (?) group ID `io.github.tomokinakamaru.silverchain`:
<img width="274" alt="screenshot" src="https://user-images.githubusercontent.com/10295467/137621209-ae23ff11-4440-4810-b3f0-1d180ac4e1ea.png">
(Since I am not familiar with Maven Central, I am not sure `io.github.tomokinakamaru.silverchain` is wrong or not, but `io.github.tomokinakamaru` seems natural  to me.)

Should we fix the following line and release again? https://github.com/tomokinakamaru/silverchain/blob/1e30439d47ee09eb73354b63021b5a1d4b8443b7/build.gradle#L108 or can we leave the group ID as it is now? I should have checked your PR more carefully before merge and release, sorry :(

**Comment by bannmann** [comment]
No, that was intentional. A group ID is not meant to represent only you as an author, but a group of related artifacts. Right now, there's only one, a jar artifact with the artifact ID `silverchain` and type `jar`. But one can easily imagine more, e.g. a `silverchain-api.jar`, a `silverchain-ui.jar` etc. Also, you may at some point have another project called `foo` which will then usually get the `io.github.tomokinakamaru` group ID.

**Comment by bannmann** [comment]
Yes, we're done here: my plugin works fine with this release and can now make its way to Central, as well. Thank you!
