### ISSUE TITLE
Document type parameter syntax

### ISSUE THREAD

**Issue by bannmann** [tomokinakamaru/silverchain#67]
https://github.com/tomokinakamaru/silverchain/issues/39#issuecomment-868169732 says
> There are now three kinds of type parameters:
> 
> 1. Ones listed in a type declaration
>        
>    1. Ones listed before `;` or without `;`
>       These type parameters are shared in a chain expression and are included in the generated type declaration. For example, if you give an input like `Foo[T]: …`, Silverchain generates `Foo<T>`.
>    2. Ones listed after `;`
>       These type parameters are shared in a chain expression but are **not** included in the generated type declaration. For example, If you give an input like `Foo[;T]: ...`, Silverchain generates `Foo` (without the type parameter). The examples [mapbuilder.ag](https://github.com/tomokinakamaru/silverchain/blob/main/src/test/resources/mapbuilder.ag) and  [listutil.ag](https://github.com/tomokinakamaru/silverchain/blob/main/src/test/resources/listutil.ag) are their usecases.
> 
> 2. Ones listed in a method declaration (New)
>        These type parameters are **not** shared in a chain expression. They are only used in the method.

This information should be documented somewhere. It doesn't fit in `README.md` or `doc/tutorial.md`, so maybe it should be the start of a `doc/ag-reference.md`.

**Comment by tomokinakamaru** [comment]
I created markdown files for AG reference (`doc/ag-reference.md`) and the usage of Javadoc support (`doc/javadoc.md`). They are not well-written yet, but they are better than nothing, I hope. If you find problems in those documents, feel free to create issues or pull requests!

**Comment by tomokinakamaru** [comment]
I will close this issue since the information is now documented in `./doc/ag-reference.md`.
